"""Sucursales verificadas usadas por el seed de la demostracion."""

from decimal import Decimal


USER_BRANCH_LIST_SOURCE = "Listado de sucursales proporcionado por el usuario el 2026-08-24"


def _source(website_url: str) -> str:
    return f"{USER_BRANCH_LIST_SOURCE} | {website_url}"


BRANCHES = (
    {
        "key": "la_anonima_san_martin",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "Centro - San Martín",
        "legacy_names": (),
        "address": "San Martín 100, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.861132"),
        "longitude": Decimal("-67.4751828"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_13_diciembre",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "13 de Diciembre",
        "legacy_names": (),
        "address": "13 de Diciembre 150, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8691672"),
        "longitude": Decimal("-67.5024295"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_goa_chile",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "GOA - Av. Chile",
        "legacy_names": (),
        "address": "Av. Chile 1625, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8829792"),
        "longitude": Decimal("-67.5394213"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_italo_dell_oro",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "Barrio Italo Dell'Oro",
        "legacy_names": (),
        "address": "Italo Dell'Oro y Calle 1, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.7952909"),
        "longitude": Decimal("-67.4422342"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_francisco_viedma",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "Francisco de Viedma",
        "legacy_names": (),
        "address": "Francisco de Viedma 102, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8366727"),
        "longitude": Decimal("-67.4785018"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_centro",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "Alem - BWT",
        "legacy_names": ("Sucursal 024 Alem", "Centro"),
        "address": "Leandro N. Alem 962, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8603638"),
        "longitude": Decimal("-67.4990773"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_atahualpa",
        "supermarket": "La Anónima",
        "city": "Comodoro Rivadavia",
        "name": "Atahualpa Yupanqui",
        "legacy_names": (),
        "address": "Atahualpa Yupanqui 400, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8753548"),
        "longitude": Decimal("-67.5194092"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "la_anonima_rada_tilly",
        "supermarket": "La Anónima",
        "city": "Rada Tilly",
        "name": "Francisco Luque",
        "legacy_names": ("Rada Tilly",),
        "address": "Francisco Luque 1200, Rada Tilly, Chubut",
        "latitude": Decimal("-45.9297447"),
        "longitude": Decimal("-67.5715408"),
        "coordinate_source": _source("https://www.laanonimaonline.com/"),
    },
    {
        "key": "carrefour_polonia",
        "supermarket": "Carrefour",
        "city": "Comodoro Rivadavia",
        "name": "Av. Polonia",
        "legacy_names": (),
        "address": "Av. Polonia 1340, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8700103"),
        "longitude": Decimal("-67.5334701"),
        "coordinate_source": _source("https://www.carrefour.com.ar/"),
    },
    {
        "key": "carrefour_comodoro",
        "supermarket": "Carrefour",
        "city": "Comodoro Rivadavia",
        "name": "Pellegrini - CYG",
        "legacy_names": ("Comodoro Centro", "Comodoro"),
        "address": "Pellegrini 851, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8615594"),
        "longitude": Decimal("-67.4800811"),
        "coordinate_source": _source("https://www.carrefour.com.ar/"),
    },
    {
        "key": "changomas_km4",
        "supermarket": "Chango Más",
        "city": "Comodoro Rivadavia",
        "name": "Km. 4",
        "legacy_names": (),
        "address": "Km. 4 Ruta Nacional 3, frente a Av. Tehuelches, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8266448"),
        "longitude": Decimal("-67.4662235"),
        "coordinate_source": _source("https://www.masonline.com.ar/"),
    },
    {
        "key": "changomas_comodoro",
        "supermarket": "Chango Más",
        "city": "Comodoro Rivadavia",
        "name": "Hiper - Enrique Girolamo",
        "legacy_names": ("Comodoro",),
        "address": "Enrique Girolamo 3100, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8832439"),
        "longitude": Decimal("-67.523354"),
        "coordinate_source": _source("https://www.masonline.com.ar/"),
    },
    {
        "key": "jumbo_comodoro",
        "supermarket": "Jumbo",
        "city": "Comodoro Rivadavia",
        "name": "Av. Ducos",
        "legacy_names": ("Comodoro", "Nombre real de la sucursal"),
        "address": "Av. Ingeniero Ducos 1325, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8733764"),
        "longitude": Decimal("-67.4927902"),
        "coordinate_source": _source("https://www.jumbo.com.ar/"),
    },
    {
        "key": "maxiconsumo_yrigoyen",
        "supermarket": "Maxiconsumo",
        "city": "Comodoro Rivadavia",
        "name": "Av. Hipólito Yrigoyen",
        "legacy_names": (),
        "address": "Av. Hipólito Yrigoyen 3057, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8857202"),
        "longitude": Decimal("-67.5213443"),
        "coordinate_source": _source("https://www.maxiconsumo.com/"),
    },
    {
        "key": "la_coope_martin_fierro",
        "supermarket": "La Coope",
        "city": "Comodoro Rivadavia",
        "name": "Martín Fierro",
        "legacy_names": (),
        "address": "Martín Fierro 748, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8671188"),
        "longitude": Decimal("-67.5219116"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "la_coope_huergo",
        "supermarket": "La Coope",
        "city": "Comodoro Rivadavia",
        "name": "C. Huergo",
        "legacy_names": (),
        "address": "C. Huergo 4116, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8583292"),
        "longitude": Decimal("-67.535497"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "la_coope_gregorio_mayo",
        "supermarket": "La Coope",
        "city": "Comodoro Rivadavia",
        "name": "Gregorio Mayo",
        "legacy_names": (),
        "address": "Gregorio Mayo 638, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8383976"),
        "longitude": Decimal("-67.4823594"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "la_coope_alejandro_maiz",
        "supermarket": "La Coope",
        "city": "Comodoro Rivadavia",
        "name": "Av. Alejandro Maíz",
        "legacy_names": (),
        "address": "Av. Alejandro Maíz 649, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.7947516"),
        "longitude": Decimal("-67.4219834"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "la_coope_kennedy_145",
        "supermarket": "La Coope",
        "city": "Comodoro Rivadavia",
        "name": "La Coope - Av. Patricios",
        "legacy_names": ("Sucursal 145 Kennedy",),
        "address": "Av. J. F. Kennedy 3091, esquina Patricios, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8789635"),
        "longitude": Decimal("-67.5366276"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "la_coope_rada_tilly",
        "supermarket": "La Coope",
        "city": "Rada Tilly",
        "name": "Av. Almte. Brown",
        "legacy_names": (),
        "address": "Acceso a Av. Almte. Brown 2074, Rada Tilly, Chubut",
        "latitude": Decimal("-45.9233262"),
        "longitude": Decimal("-67.5614139"),
        "coordinate_source": _source("https://www.lacoopeencasa.coop/"),
    },
    {
        "key": "diarco_yrigoyen",
        "supermarket": "Diarco",
        "city": "Comodoro Rivadavia",
        "name": "Av. Hipólito Yrigoyen",
        "legacy_names": (),
        "address": "Av. Hipólito Yrigoyen 1848, Comodoro Rivadavia, Chubut",
        "latitude": Decimal("-45.8767236"),
        "longitude": Decimal("-67.5024303"),
        "coordinate_source": _source("https://www.diarco.com.ar/"),
    },
)
