"""create initial price dss schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-23 19:15:36.339400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('categoria_padre_id', sa.Uuid(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['categoria_producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_categoria_producto_nombre')
    )
    op.create_index('ix_categoria_producto_activo', 'categoria_producto', ['activo'], unique=False)
    op.create_index('ix_categoria_producto_nombre', 'categoria_producto', ['nombre'], unique=False)
    op.create_index('ix_categoria_producto_padre_id', 'categoria_producto', ['categoria_padre_id'], unique=False)
    op.create_table('marca',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_marca_nombre')
    )
    op.create_index('ix_marca_activo', 'marca', ['activo'], unique=False)
    op.create_index('ix_marca_nombre', 'marca', ['nombre'], unique=False)
    op.create_table('provincia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_iso', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso', name='uq_provincia_codigo_iso'),
    sa.UniqueConstraint('nombre', name='uq_provincia_nombre')
    )
    op.create_index('ix_provincia_nombre', 'provincia', ['nombre'], unique=False)
    op.create_table('supermercado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('sitio_web', sa.String(length=2048), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_supermercado_nombre')
    )
    op.create_index('ix_supermercado_activo', 'supermercado', ['activo'], unique=False)
    op.create_index('ix_supermercado_nombre', 'supermercado', ['nombre'], unique=False)
    op.create_table('ciudad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provincia_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_postal', sa.String(length=32), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.CheckConstraint('latitud IS NULL OR latitud BETWEEN -90 AND 90', name='ck_ciudad_latitud_rango'),
    sa.CheckConstraint('longitud IS NULL OR longitud BETWEEN -180 AND 180', name='ck_ciudad_longitud_rango'),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provincia_id', 'nombre', name='uq_ciudad_provincia_nombre')
    )
    op.create_index('ix_ciudad_nombre', 'ciudad', ['nombre'], unique=False)
    op.create_index('ix_ciudad_provincia_id', 'ciudad', ['provincia_id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('marca_id', sa.Uuid(), nullable=True),
    sa.Column('nombre_normalizado', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('unidad_medida', sa.String(length=64), nullable=True),
    sa.Column('contenido_neto', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('codigo_interno', sa.String(length=128), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('contenido_neto IS NULL OR contenido_neto > 0', name='ck_producto_contenido_neto_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_producto.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno', name='uq_producto_codigo_interno')
    )
    op.create_index('ix_producto_activo', 'producto', ['activo'], unique=False)
    op.create_index('ix_producto_categoria_id', 'producto', ['categoria_id'], unique=False)
    op.create_index('ix_producto_marca_id', 'producto', ['marca_id'], unique=False)
    op.create_index('ix_producto_nombre_normalizado', 'producto', ['nombre_normalizado'], unique=False)
    op.create_table('producto_fuente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('supermercado_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_original', sa.String(length=500), nullable=False),
    sa.Column('codigo_externo', sa.String(length=255), nullable=True),
    sa.Column('url_producto', sa.String(length=2048), nullable=True),
    sa.Column('unidad_original', sa.String(length=64), nullable=True),
    sa.Column('confianza_match', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('confianza_match IS NULL OR confianza_match BETWEEN 0 AND 1', name='ck_producto_fuente_confianza_match_rango'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['supermercado_id'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supermercado_id', 'codigo_externo', name='uq_producto_fuente_supermercado_codigo_externo')
    )
    op.create_index('ix_producto_fuente_activo', 'producto_fuente', ['activo'], unique=False)
    op.create_index('ix_producto_fuente_nombre_original', 'producto_fuente', ['nombre_original'], unique=False)
    op.create_index('ix_producto_fuente_producto_id', 'producto_fuente', ['producto_id'], unique=False)
    op.create_index('ix_producto_fuente_supermercado_id', 'producto_fuente', ['supermercado_id'], unique=False)
    op.create_table('sucursal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supermercado_id', sa.Uuid(), nullable=False),
    sa.Column('ciudad_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('latitud BETWEEN -90 AND 90', name='ck_sucursal_latitud_rango'),
    sa.CheckConstraint('longitud BETWEEN -180 AND 180', name='ck_sucursal_longitud_rango'),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['supermercado_id'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supermercado_id', 'nombre', 'direccion', name='uq_sucursal_supermercado_nombre_direccion')
    )
    op.create_index('ix_sucursal_activo', 'sucursal', ['activo'], unique=False)
    op.create_index('ix_sucursal_ciudad_id', 'sucursal', ['ciudad_id'], unique=False)
    op.create_index('ix_sucursal_latitud_longitud', 'sucursal', ['latitud', 'longitud'], unique=False)
    op.create_index('ix_sucursal_supermercado_id', 'sucursal', ['supermercado_id'], unique=False)
    op.create_table('precio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_fuente_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=8), server_default='ARS', nullable=False),
    sa.Column('fecha_relevamiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('promocion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(trim(moneda)) > 0', name='ck_precio_moneda_no_vacia'),
    sa.CheckConstraint('precio >= 0', name='ck_precio_valor_no_negativo'),
    sa.ForeignKeyConstraint(['producto_fuente_id'], ['producto_fuente.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precio_disponible', 'precio', ['disponible'], unique=False)
    op.create_index('ix_precio_fecha_relevamiento', 'precio', ['fecha_relevamiento'], unique=False)
    op.create_index('ix_precio_producto_fuente_id', 'precio', ['producto_fuente_id'], unique=False)
    op.create_index('ix_precio_producto_fuente_sucursal_fecha', 'precio', ['producto_fuente_id', 'sucursal_id', 'fecha_relevamiento'], unique=False)
    op.create_index('ix_precio_promocion', 'precio', ['promocion'], unique=False)
    op.create_index('ix_precio_sucursal_id', 'precio', ['sucursal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_precio_sucursal_id', table_name='precio')
    op.drop_index('ix_precio_promocion', table_name='precio')
    op.drop_index('ix_precio_producto_fuente_sucursal_fecha', table_name='precio')
    op.drop_index('ix_precio_producto_fuente_id', table_name='precio')
    op.drop_index('ix_precio_fecha_relevamiento', table_name='precio')
    op.drop_index('ix_precio_disponible', table_name='precio')
    op.drop_table('precio')
    op.drop_index('ix_sucursal_supermercado_id', table_name='sucursal')
    op.drop_index('ix_sucursal_latitud_longitud', table_name='sucursal')
    op.drop_index('ix_sucursal_ciudad_id', table_name='sucursal')
    op.drop_index('ix_sucursal_activo', table_name='sucursal')
    op.drop_table('sucursal')
    op.drop_index('ix_producto_fuente_supermercado_id', table_name='producto_fuente')
    op.drop_index('ix_producto_fuente_producto_id', table_name='producto_fuente')
    op.drop_index('ix_producto_fuente_nombre_original', table_name='producto_fuente')
    op.drop_index('ix_producto_fuente_activo', table_name='producto_fuente')
    op.drop_table('producto_fuente')
    op.drop_index('ix_producto_nombre_normalizado', table_name='producto')
    op.drop_index('ix_producto_marca_id', table_name='producto')
    op.drop_index('ix_producto_categoria_id', table_name='producto')
    op.drop_index('ix_producto_activo', table_name='producto')
    op.drop_table('producto')
    op.drop_index('ix_ciudad_provincia_id', table_name='ciudad')
    op.drop_index('ix_ciudad_nombre', table_name='ciudad')
    op.drop_table('ciudad')
    op.drop_index('ix_supermercado_nombre', table_name='supermercado')
    op.drop_index('ix_supermercado_activo', table_name='supermercado')
    op.drop_table('supermercado')
    op.drop_index('ix_provincia_nombre', table_name='provincia')
    op.drop_table('provincia')
    op.drop_index('ix_marca_nombre', table_name='marca')
    op.drop_index('ix_marca_activo', table_name='marca')
    op.drop_table('marca')
    op.drop_index('ix_categoria_producto_padre_id', table_name='categoria_producto')
    op.drop_index('ix_categoria_producto_nombre', table_name='categoria_producto')
    op.drop_index('ix_categoria_producto_activo', table_name='categoria_producto')
    op.drop_table('categoria_producto')
    # ### end Alembic commands ###
